# Generated by Django 6.0.3 on 2026-03-22 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.CreateModel(
            name='GuideContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='static/')),
                ('fb_link', models.URLField()),
                ('insta_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('discription', models.TextField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.guide')),
            ],
        ),
    ]
