# Generated by Django 6.0.3 on 2026-03-22 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_alter_guide_photo_guidecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels',
            name='best_guide',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='travels.guide'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='day_by_day',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='travels.dayplan'),
        ),
    ]
