# Generated by Django 6.0.3 on 2026-03-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_alter_travels_best_guide_alter_travels_day_by_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayplan',
            name='travel',
        ),
    ]
