# Generated by Django 6.0.3 on 2026-03-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_remove_dayplan_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
