# Generated by Django 6.0.3 on 2026-03-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_dayplan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidecontact',
            name='image',
        ),
    ]
