# Generated by Django 6.0.3 on 2026-03-22 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_remove_guidecontact_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AlterField(
            model_name='review',
            name='travel',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='travels.travels'),
        ),
    ]
