# Generated by Django 6.0.3 on 2026-03-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_remove_review_user_alter_review_travel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
