# Generated by Django 6.0.3 on 2026-03-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0009_customers_guide_charges_travels_trending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='photo',
        ),
        migrations.AddField(
            model_name='guide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='guides/'),
        ),
        migrations.AddField(
            model_name='travels',
            name='country',
            field=models.CharField(default='Nepal', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='image',
            field=models.ImageField(upload_to='customers/'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
