# Generated by Django 6.0.3 on 2026-03-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0010_remove_guide_photo_guide_image_travels_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
