# Generated by Django 6.0.3 on 2026-03-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0011_alter_guide_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='image',
            field=models.ImageField(upload_to='static/Customers/'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/Guides/'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='image',
            field=models.ImageField(upload_to='static/Travels/'),
        ),
    ]
