# Generated by Django 6.0.3 on 2026-03-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0012_alter_customers_image_alter_guide_image_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        """
                        SET @has_old := (
                            SELECT COUNT(*)
                            FROM information_schema.COLUMNS
                            WHERE TABLE_SCHEMA = DATABASE()
                              AND TABLE_NAME = 'travels_guidecontact'
                              AND COLUMN_NAME = 'discription'
                        );
                        SET @has_new := (
                            SELECT COUNT(*)
                            FROM information_schema.COLUMNS
                            WHERE TABLE_SCHEMA = DATABASE()
                              AND TABLE_NAME = 'travels_guidecontact'
                              AND COLUMN_NAME = 'description'
                        );
                        SET @sql := IF(
                            @has_old = 1 AND @has_new = 0,
                            'ALTER TABLE travels_guidecontact CHANGE COLUMN discription description TEXT NOT NULL',
                            'SELECT 1'
                        );
                        PREPARE stmt FROM @sql;
                        EXECUTE stmt;
                        DEALLOCATE PREPARE stmt;
                        """
                    ),
                    reverse_sql=(
                        """
                        SET @has_old := (
                            SELECT COUNT(*)
                            FROM information_schema.COLUMNS
                            WHERE TABLE_SCHEMA = DATABASE()
                              AND TABLE_NAME = 'travels_guidecontact'
                              AND COLUMN_NAME = 'discription'
                        );
                        SET @has_new := (
                            SELECT COUNT(*)
                            FROM information_schema.COLUMNS
                            WHERE TABLE_SCHEMA = DATABASE()
                              AND TABLE_NAME = 'travels_guidecontact'
                              AND COLUMN_NAME = 'description'
                        );
                        SET @sql := IF(
                            @has_old = 0 AND @has_new = 1,
                            'ALTER TABLE travels_guidecontact CHANGE COLUMN description discription TEXT NOT NULL',
                            'SELECT 1'
                        );
                        PREPARE stmt FROM @sql;
                        EXECUTE stmt;
                        DEALLOCATE PREPARE stmt;
                        """
                    ),
                ),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name='guidecontact',
                    old_name='discription',
                    new_name='description',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        """
                        SET @has_travel := (
                            SELECT COUNT(*)
                            FROM information_schema.COLUMNS
                            WHERE TABLE_SCHEMA = DATABASE()
                              AND TABLE_NAME = 'travels_review'
                              AND COLUMN_NAME = 'travel_id'
                        );
                        SET @sql := IF(
                            @has_travel = 1,
                            'ALTER TABLE travels_review DROP COLUMN travel_id',
                            'SELECT 1'
                        );
                        PREPARE stmt FROM @sql;
                        EXECUTE stmt;
                        DEALLOCATE PREPARE stmt;
                        """
                    ),
                    reverse_sql='SELECT 1',
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='review',
                    name='travel',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        """
                        SET @has_user := (
                            SELECT COUNT(*)
                            FROM information_schema.COLUMNS
                            WHERE TABLE_SCHEMA = DATABASE()
                              AND TABLE_NAME = 'travels_review'
                              AND COLUMN_NAME = 'user_id'
                        );
                        SET @sql := IF(
                            @has_user = 0,
                            'ALTER TABLE travels_review ADD COLUMN user_id BIGINT NULL',
                            'SELECT 1'
                        );
                        PREPARE stmt FROM @sql;
                        EXECUTE stmt;
                        DEALLOCATE PREPARE stmt;
                        """
                    ),
                    reverse_sql='SELECT 1',
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='review',
                    name='user',
                    field=models.ForeignKey(blank=True, default='Bimal', on_delete=django.db.models.deletion.CASCADE, to='travels.customers'),
                    preserve_default=False,
                ),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
