# Generated by Django 6.0.3 on 2026-03-29 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0014_alter_review_user'),
    ]

    operations = []
