# Generated by Django 6.0.3 on 2026-03-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0015_rename_description_guidecontact_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='languages',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
