# Generated by Django 6.0.3 on 2026-03-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0016_guide_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
