# Generated by Django 6.0.3 on 2026-03-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0017_guide_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='rating',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
