# Generated by Django 6.0.3 on 2026-03-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0018_alter_guide_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels',
            name='rating',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
