# Generated by Django 6.0.3 on 2026-03-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0019_travels_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
