# Generated by Django 6.0.3 on 2026-04-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0020_travels_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
