# Generated by Django 6.0.3 on 2026-04-01 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0021_alter_review_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='customer',
        ),
    ]
