# Generated by Django 6.0.3 on 2026-04-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0024_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='tour',
            new_name='travel',
        ),
    ]
