# Generated by Django 6.0.3 on 2026-08-14 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0025_rename_tour_booking_travel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='travel',
        ),
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travels.customers'),
        ),
    ]
